In [2]:
# Import the library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm

In [4]:
# Load the data

df = pd.read_csv("../data/CO2_data.csv")
df.head()

   T [C]  P_vap [kPa]  H_vap [J/g]  rho_vap [g/cm3]  rho_liq [g/cm3]
0  -56.6        518.3          NaN              NaN            1.179
1  -56.0        531.8          NaN              NaN            1.177
2  -54.0        579.1          NaN              NaN            1.169
3  -52.0        629.6          NaN              NaN            1.162
4  -50.0        683.4          NaN              NaN            1.155

In [6]:
# Information about the data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   T [C]            72 non-null     float64
 1   P_vap [kPa]      72 non-null     float64
 2   H_vap [J/g]      57 non-null     float64
 3   rho_vap [g/cm3]  57 non-null     float64
 4   rho_liq [g/cm3]  72 non-null     float64
dtypes: float64(5)
memory usage: 2.9 KB

In [7]:
df.describe()

           T [C]  P_vap [kPa]  H_vap [J/g]  rho_vap [g/cm3]  rho_liq [g/cm3]
count  72.000000    72.000000    57.000000        57.000000        72.000000
mean   -7.696944  3318.288889   208.747544         0.132168         0.924410
std    24.977866  2016.721511    70.314376         0.093078         0.159318
min   -56.600000   518.300000     0.000000         0.038460         0.464100
25%   -25.837500  1672.000000   169.100000         0.063140         0.831700
50%    -6.115000  2954.500000   227.300000         0.101300         0.941800
75%    13.057500  4830.750000   264.500000         0.171700         1.021725
max    31.100000  7391.000000   292.900000         0.464100         1.179000

In [8]:
# Dropping NaN values
df = df.dropna(subset=['H_vap [J/g]', 'rho_vap [g/cm3]'])
df.shape

(57, 5)